### ISSUE TITLE
Conduit tool not work with fifo queue

### ISSUE THREAD

**Issue by illomi7** [GaruGaru/conduit#4]
Hi,
I need to move message from two fifo queue but it doesn't work and give me this error.

> panic: InvalidParameterValue: The request must contain the parameter MessageGroupId.
> 	status code: 400, request id: 0b669358-d3a0-549c-a48b-c6b95a1d57f8

Can you solve it?

Thanks,
Matteo.

**Comment by GaruGaru** [comment]
Hi @illomi7  thank you for the feedback
The issue has been fixed in facd2e58e2a9e7d815da5c495caf5489ae1edacd

Have a nice day !

**Comment by illomi7** [comment]
Hi @GaruGaru thank you very much.
